### ISSUE TITLE
cmn: service Start and Stop cannot safely be called from different routines 

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tmlibs#127]
For instance, this

```
func TestMConnectionStartStop(t *testing.T) {
	server, client := NetPipe()
	mconn := createTestMConnection(client)
	go func() { mconn.Start() }()
	mconn.Stop()
}
```

panics:

```
--- FAIL: TestMConnectionStartStop (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13bc4d4]

goroutine 20 [running]:
testing.tRunner.func1(0xc4201de0f0)
        /usr/local/opt/go/libexec/src/testing/testing.go:711 +0x5d9
panic(0x1492280, 0x18479f0)
        /usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x2a2
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*RepeatTimer).Stop(0x0)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/repeat_timer.go:172 +0x34                                                                                                                          
github.com/tendermint/tendermint/p2p/conn.(*MConnection).OnStop(0xc420142600)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/p2p/conn/connection.go:186 +0x85
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Stop(0xc420142600, 0x162b928, 0xc420142600)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/service.go:145 +0x2a8                                                                                                                              
github.com/tendermint/tendermint/p2p/conn.TestMConnectionStartStop(0xc4201de0f0)
        /Users/ethanbuchman/programming/goApps/src/github.com/tendermint/tendermint/p2p/conn/connection_test.go:38 +0x4b9
```

I believe it's because the service doesn't hold locks, it just does a CAS op, and it's possible the initialization hasn't finished by the time Stop is called.

**Comment by ebuchman** [comment]
This is of course part of the spec.

We can probably figure out how to write a better test instead of changing Service.
