### ISSUE TITLE
common: non-deterministic failure with RepeatTimer

### ISSUE THREAD

**Issue by melekes** [tendermint/tmlibs#138]
```
--- FAIL: TestRepeat (10.03s)
panic: expected RepeatTimer to fire [recovered]
        panic: expected RepeatTimer to fire

goroutine 99 [running]:
testing.tRunner.func1(0xc420218000)
        /usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x6f6800, 0x7af0b0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/tendermint/tmlibs/common.TestRepeat.func2(0xc420218000, 0xc42021e000, 0x1)
        /go/src/github.com/tendermint/tmlibs/common/repeat_timer_test.go:38 +0x1c2
github.com/tendermint/tmlibs/common.TestRepeat(0xc420218000)
        /go/src/github.com/tendermint/tmlibs/common/repeat_timer_test.go:80 +0x334
testing.tRunner(0xc420218000, 0x788188)
        /usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:789 +0x2de
exit status 2
```

**Comment by melekes** [comment]
ok. not observing these anymore after sdk2 branch was merged.
