### ISSUE TITLE
common/BitArray: all setters whose arguments take in another *BitArray should first check for nil-ity

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tmlibs#145]
I've been auditing usages of BitArray and found that similiar to this embarrassing bug https://github.com/tendermint/tendermint/issues/1169 that we fixed with https://github.com/tendermint/tmlibs/pull/136 we should check to see that the other *BitArray being passed in is non-nil

A simple exhibit is this test that fails at head https://github.com/tendermint/tmlibs/commit/19e818fdf79aa9290661acfe45a3f4dfd4e996a9 after
```diff
diff --git a/common/bit_array_test.go b/common/bit_array_test.go
index e4ac8bf..3d4b3b3 100644
--- a/common/bit_array_test.go
+++ b/common/bit_array_test.go
@@ -46,6 +46,8 @@ func TestOr(t *testing.T) {
 	bA2, _ := randBitArray(31)
 	bA3 := bA1.Or(bA2)
 
+	bA1.Or(nil)
+
 	if bA3.Bits != 51 {
 		t.Error("Expected max bits")
 	}
```

with stack trace
```shell
$ go test -v -run=Or
=== RUN   TestOr
--- FAIL: TestOr (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12a71cb]

goroutine 20 [running]:
testing.tRunner.func1(0xc4201560f0)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:742 +0x29d
panic(0x1304e40, 0x152a4f0)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/panic.go:505 +0x229
github.com/tendermint/tmlibs/common.(*BitArray).Or(0xc4200a3620, 0x0, 0x0)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tmlibs/common/bit_array.go:107 +0x7b
github.com/tendermint/tmlibs/common.TestOr(0xc4201560f0)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tmlibs/common/bit_array_test.go:49 +0x8c
testing.tRunner(0xc4201560f0, 0x13818d0)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:824 +0x2e0
exit status 2
FAIL	github.com/tendermint/tmlibs/common	0.014s
```

**Comment by odeke-em** [comment]
Fixed by https://github.com/tendermint/tmlibs/pull/147 which has been merged into develop.
