### ISSUE TITLE
Is repeat_timer_test non-deterministic?

### ISSUE THREAD

**Issue by sunnya97** [tendermint/tmlibs#187]
Logs from my computer running `make test` right after each other.  First time it fails, second time it passes:

Also, would explain why #186 is failing?

```
sunnys-mbp-2:tmlibs sunnya97$ make test
go test -tags gcc `glide novendor`
?   	github.com/tendermint/tmlibs/test	[no test files]
ok  	github.com/tendermint/tmlibs/clist	(cached)
ok  	github.com/tendermint/tmlibs/merkle	(cached)
ok  	github.com/tendermint/tmlibs/autofile	(cached)
ok  	github.com/tendermint/tmlibs/cli	(cached)
ok  	github.com/tendermint/tmlibs/cli/flags	(cached)
--- FAIL: TestRepeat (10.03s)
panic: expected RepeatTimer to fire [recovered]
	panic: expected RepeatTimer to fire

goroutine 212 [running]:
testing.tRunner.func1(0xc4202dc0f0)
	/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:742 +0x29d
panic(0x12ea0c0, 0x13a5580)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/tendermint/tmlibs/common.TestRepeat.func2(0xc4202dc0f0, 0xc4202c80a0, 0x1)
	/Users/sunnya97/go/src/github.com/tendermint/tmlibs/common/repeat_timer_test.go:36 +0x1a4
github.com/tendermint/tmlibs/common.TestRepeat(0xc4202dc0f0)
	/Users/sunnya97/go/src/github.com/tendermint/tmlibs/common/repeat_timer_test.go:78 +0x31f
testing.tRunner(0xc4202dc0f0, 0x137fe80)
	/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:824 +0x2e0
FAIL	github.com/tendermint/tmlibs/common	10.217s
?   	github.com/tendermint/tmlibs/version	[no test files]
ok  	github.com/tendermint/tmlibs/flowrate	(cached)
ok  	github.com/tendermint/tmlibs/db	0.219s
ok  	github.com/tendermint/tmlibs/pubsub	(cached)
ok  	github.com/tendermint/tmlibs/pubsub/query	(cached)
?   	github.com/tendermint/tmlibs/pubsub/query/fuzz_test	[no test files]
ok  	github.com/tendermint/tmlibs/log	(cached)
ok  	github.com/tendermint/tmlibs/events	(cached)
make: *** [test] Error 1

sunnys-mbp-2:tmlibs sunnya97$ make test
go test -tags gcc `glide novendor`
?   	github.com/tendermint/tmlibs/test	[no test files]
ok  	github.com/tendermint/tmlibs/clist	(cached)
ok  	github.com/tendermint/tmlibs/merkle	(cached)
ok  	github.com/tendermint/tmlibs/autofile	(cached)
ok  	github.com/tendermint/tmlibs/cli	(cached)
ok  	github.com/tendermint/tmlibs/cli/flags	(cached)
ok  	github.com/tendermint/tmlibs/common	0.739s
?   	github.com/tendermint/tmlibs/version	[no test files]
ok  	github.com/tendermint/tmlibs/flowrate	(cached)
ok  	github.com/tendermint/tmlibs/db	(cached)
ok  	github.com/tendermint/tmlibs/pubsub	(cached)
ok  	github.com/tendermint/tmlibs/pubsub/query	(cached)
?   	github.com/tendermint/tmlibs/pubsub/query/fuzz_test	[no test files]
ok  	github.com/tendermint/tmlibs/log	(cached)
ok  	github.com/tendermint/tmlibs/events	(cached)
```

**Comment by zramsay** [comment]
doesn't seem to have come in awhile. re-open in Tendermint Core repo if encountered again
