### ISSUE TITLE
db/memdb: populating too many values causes memdb.MemDBIterator.Key() index overrun and crash

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tmlibs#36]
The test in PR https://github.com/tendermint/merkleeyes/pull/40 revealed perhaps an index overrun and a crash in memdb in which it seems like memDBIterator.Keys()'s last index tracker is overly incremented beyond the keys that can be looked up.

### Symptoms:
In the code and patch that proceeds this section, pay attention to the debug in the recovery after the crash
```shell
klen: 1999738 it.last: 1999738
```
where we get that by printing ```len(it.keys), it.last``` i.e

```go
func (it *memDBIterator) Key() []byte {
        defer func() {
                if err := recover(); err != nil {
                        stack := make([]byte, 1024*1024)
                        _ = runtime.Stack(stack, true)
                        fmt.Printf("\033[32mklen: %d it.last: %d\033[00m\nstack: %s\n", len(it.keys), it.last, stack)
                }
        }()
        return []byte(it.keys[it.last])
}
```

### Code to reproduce
```go
package test

import (
	"io/ioutil"
	"testing"

	"github.com/tendermint/go-wire"
	"github.com/tendermint/merkleeyes/iavl"
	"github.com/tendermint/tmlibs/common"
	"github.com/tendermint/tmlibs/db"
)

func i2b(i int) []byte {
	bz := make([]byte, 4)
	wire.PutInt32(bz, int32(i))
	return bz
}

func TestIAVLTreeFdump(t *testing.T) {
	db := db.NewDB("test", db.MemDBBackendStr, "")
	tree := iavl.NewIAVLTree(100000, db)
	for i := 0; i < 1000000; i++ {
		tree.Set(i2b(int(common.RandInt32())), nil)
		if i > 990000 && i%1000 == 999 {
			tree.Save()
		}
	}
	tree.Save()

	// insert lots of info and store the bytes
	for i := 0; i < 200; i++ {
		key, value := common.RandStr(20), common.RandStr(200)
		tree.Set([]byte(key), []byte(value))
	}

	tree.Fdump(ioutil.Discard, true, &iavl.KeyValueMapping{
		Key:   func(b []byte) string { return string(b) },
		Value: func(b []byte) string { return string(b) },
	})
}
```

### Patch to apply to tmlibs
```diff
diff --git a/db/mem_db.go b/db/mem_db.go
index 2866242..b5ee0c3 100644
--- a/db/mem_db.go
+++ b/db/mem_db.go
@@ -2,6 +2,7 @@ package db
 
 import (
 	"fmt"
+	"runtime"
 	"sync"
 )
 
@@ -90,6 +91,13 @@ func (it *memDBIterator) Next() bool {
 }
 
 func (it *memDBIterator) Key() []byte {
+	defer func() {
+		if err := recover(); err != nil {
+			stack := make([]byte, 1024*1024)
+			_ = runtime.Stack(stack, true)
+			fmt.Printf("\033[32mklen: %d it.last: %d\033[00m\nstack: %s\n", len(it.keys), it.last, stack)
+		}
+	}()
 	return []byte(it.keys[it.last])
 }
```
Gives this stack trace

```shell
=== RUN   TestIAVLTreeFdump
klen: 1999738 it.last: 1999738
stack: goroutine 8 [running]:
github.com/tendermint/tmlibs/db.(*memDBIterator).Key.func1(0xc421b44e10)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tmlibs/db/mem_db.go:97 +0xb2
panic(0x4467120, 0x4781df0)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/panic.go:491 +0x283
github.com/tendermint/tmlibs/db.(*memDBIterator).Key(0xc421b44e10, 0x0, 0x0, 0x0)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tmlibs/db/mem_db.go:101 +0xde
github.com/tendermint/merkleeyes/iavl.(*IAVLTree).Fdump(0xc4201aece0, 0x4748180, 0x47b1d30, 0x1, 0xc420521f88)
	/Users/emmanuelodeke/go/src/github.com/tendermint/merkleeyes/iavl/iavl_tree_dump.go:148 +0xc2
_/Users/emmanuelodeke/Desktop/openSrc/bugs/tendermint/merkleeyes.TestIAVLTreeFdump(0xc4201dc0f0)
	/Users/emmanuelodeke/Desktop/openSrc/bugs/tendermint/merkleeyes/iavl_tree_dump_test.go:36 +0x32d
testing.tRunner(0xc4201dc0f0, 0x4501080)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:749 +0xd0
created by testing.(*T).Run
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:792 +0x2de

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4201dc000, 0x44eb27d, 0x11, 0x4501080, 0x407c866)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:793 +0x2fc
testing.runTests.func1(0xc4201dc000)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1007 +0x64
testing.tRunner(0xc4201dc000, 0xc4201cfde0)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:749 +0xd0
testing.runTests(0xc4201b27e0, 0x47828e0, 0x1, 0x1, 0x20)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:1005 +0x2d8
testing.(*M).Run(0xc42051ff18, 0xc4201cff70)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/testing/testing.go:924 +0x111
main.main()
	_/Users/emmanuelodeke/Desktop/openSrc/bugs/tendermint/merkleeyes/_test/_testmain.go:44 +0xdb

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/sigqueue.go:131 +0xa7
os/signal.loop()
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 7 [chan receive]:
github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x478d1e0)
	/Users/emmanuelodeke/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics/meter.go:221 +0x31
created by github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics.NewMeter
	/Users/emmanuelodeke/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics/meter.go:40 +0x127
```

**Comment by ebuchman** [comment]
fixed here: https://github.com/tendermint/tmlibs/commit/8f1dea89f5a7b2c2d883a0310c5ef94d8980bcdb
