### ISSUE TITLE
missing key

### ISSUE THREAD

**Issue by zramsay** [tendermint/tmlibs#41]
@ebuchman commented on [Fri Jan 13 2017](https://github.com/tendermint/go-merkle/issues/20)

error came up randomly after working fine for a bit

```
panic: Paniced on a Sanity Check: Value missing for key 724A3FD288A313961EBE9C1A37EFFBBC65C9273D

goroutine 26 [running]:
panic(0x8960c0, 0xc8201c10c0)
        /home/balloo/go/src/runtime/panic.go:464 +0x3e6
github.com/tendermint/abci/vendor/github.com/tendermint/go-common.PanicSanity(0x8960c0, 0xc8201c10a0)
        /home/balloo/goApps/src/github.com/tendermint/abci/vendor/github.com/tendermint/go-common/errors.go:26 +0xf5
github.com/tendermint/abci/vendor/github.com/tendermint/go-merkle.(*nodeDB).GetNode(0xc820122be0, 0xc820126fc0, 0xc82012bb60, 0x14, 0x14, 0x0)
        /home/balloo/goApps/src/github.com/tendermint/abci/vendor/github.com/tendermint/go-merkle/iavl_tree.go:236 +0x34b
github.com/tendermint/abci/vendor/github.com/tendermint/go-merkle.(*IAVLNode).getRightNode(0xc820085d60, 0xc820126fc0, 0x30)
        /home/balloo/goApps/src/github.com/tendermint/abci/vendor/github.com/tendermint/go-merkle/iavl_node.go:364 +0x6d
github.com/tendermint/abci/vendor/github.com/tendermint/go-merkle.(*IAVLNode).has(0xc820085d60, 0xc820126fc0, 0xc820137e60, 0x25, 0x30, 0x25)
        /home/balloo/goApps/src/github.com/tendermint/abci/vendor/github.com/tendermint/go-merkle/iavl_node.go:108 +0x13a
github.com/tendermint/abci/vendor/github.com/tendermint/go-merkle.(*IAVLNode).has(0xc820085cc0, 0xc820126fc0, 0xc820137e60, 0x25, 0x30, 0xfa)
        /home/balloo/goApps/src/github.com/tendermint/abci/vendor/github.com/tendermint/go-merkle/iavl_node.go:106 +0x11e
github.com/tendermint/abci/vendor/github.com/tendermint/go-merkle.(*IAVLNode).has(0xc820085c20, 0xc820126fc0, 0xc820137e60, 0x25, 0x30, 0xfa)
```

---

@jaekwon commented on [Fri Jan 13 2017](https://github.com/tendermint/go-merkle/issues/20#issuecomment-272561992)

Is there more context?

**Comment by zramsay** [comment]
Issue moved to [tendermint/merkleeyes #42](https://github.com/tendermint/merkleeyes/issues/42) via [**ZenHub**](https://www.zenhub.com/)
